name: Deploy HttpClientMock package

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'

      - name: Update version
        if: ${{ github.event_name == 'push' }}
        run: gitversion /updatecsproj

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Build and pack NuGet package
        run: dotnet pack ./src -c Release --include-symbols -o nuget /p:PackageVersion=$(gitversion /showvariable NuGetVersionV2)

      - name: Publish NuGet package
        run: dotnet nuget push nuget/*.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_ORG_API_KEY }} --skip-duplicate --no-symbols true
